/**
 * Trigger a Pipeline over a ref, and materialize the initial Graph.
 * spec.md "Definisi Pipeline" + "Semantik eksekusi"; CONTEXT.md "Pipeline",
 * "Run", "Graph".
 *
 * Pipeline identity is host Repository + file path — there is no
 * `pipelines` table (spec: "Definisi Pipeline"). The definition is always
 * read from the ref being triggered, through `GitHost`, never from a
 * default branch and never from a cache (that cache is Automation's, issue
 * #18 — a manual trigger reads live every time).
 *
 * Materialization scope, deliberately narrower than the full "hybrid"
 * picture ticket 06-dag-execution-semantics.md describes: this issue
 * inserts a StepRun, outcome `ready`, for exactly the Steps whose `after:`
 * is empty and which are not themselves a fan-out source (`branches:` /
 * `branchesFrom:`). Every other Step — anything with an unmet dependency,
 * fan-out or not — is intentionally left unmaterialized. Two facts about
 * this codebase force that boundary, not a reading of convenience:
 *
 *  1. `step_runs.outcome`'s CHECK constraint is closed over exactly
 *     `ready | running | awaiting-human | succeeded | failed | skipped |
 *     cancelled` — there is no "materialized but blocked on an upstream
 *     Step" value. Giving a Step with unmet dependencies `outcome: 'ready'`
 *     would make it claimable immediately: `claim_step_run.sql` (already
 *     shipped, already has seven green contract tests) filters purely on
 *     `outcome = 'ready'`, with no join back to its dependencies.
 *  2. Nothing in this issue's scope can ever move a StepRun to a terminal
 *     state — that is issue #5's `/result` endpoint. The event-driven
 *     "evaluate downstream when an upstream Step finishes" mechanism the
 *     06-dag ticket describes has no caller yet within this issue, and
 *     code with no caller is exactly what YAGNI asks us not to write.
 *
 * See the written report for this as an open question for review.
 */
import { and, asc, count, desc, eq, inArray, isNotNull, isNull, lt } from "drizzle-orm";
import {
  generateId,
  validatePipelineDefinition,
  type Id,
  type Pipeline,
  type ValidationIssue,
} from "@factory/shared";
import {
  artifacts,
  projects,
  questions,
  repositories,
  runs,
  secrets,
  serviceAccounts,
  stepRuns,
} from "../db/schema.js";
import type { AppDeps } from "../deps.js";
import type { Database } from "../db/client.js";
import type { Principal } from "./principal.js";
import { requireProjectMembership } from "./projects.js";
import { recordAuditEvent } from "./audit.js";
import { DomainValidationError, NotFoundError } from "./errors.js";
import { RefNotFoundError, type RepoRef } from "./git-host.js";
import { materializeFanOut, isFanOutStep } from "./graph-advance.js";

export type Run = typeof runs.$inferSelect;
export type StepRun = typeof stepRuns.$inferSelect;

/**
 * Combined cap on (definition YAML text + every prompt file it references),
 * enforced before a Run row is ever written (spec: "batas ukuran
 * ditegakkan saat validasi"). Not a number spec.md states explicitly — see
 * the written report.
 */
export const MAX_TOTAL_DEFINITION_BYTES = 2 * 1024 * 1024;

export interface TriggerRunInput {
  /** Client-generated (spec: "Id Run dibangkitkan klien") — a double-triggered id is rejected by the `runs` primary key, not by an application-level guard. */
  id: Id<"run">;
  repositoryId: Id<"repository">;
  pipelinePath: string;
  refBranch: string;
}

export interface TriggeredRun {
  run: Run;
  stepRuns: StepRun[];
}

/**
 * Everything `materializeRun` needs beyond the already-validated definition.
 * Shared by the manual trigger (issue #4) and Automation (issue #18) — the
 * two paths differ only in who the principal is, which ref the definition
 * was read from, and how a unique violation is interpreted; the birth of the
 * Run and its initial Graph is one transaction shape.
 */
export interface MaterializeRunInput {
  /** Server-generated by Automation; client-generated by the manual trigger. */
  id: Id<"run">;
  project: typeof projects.$inferSelect;
  pipelineRepository: typeof repositories.$inferSelect;
  pipelinePath: string;
  refBranch: string;
  refSha: string;
  triggerKind: "manual" | "automation";
  triggeredByPrincipalId: Id<"user"> | Id<"serviceaccount">;
  credentialPrincipalId: Id<"user"> | Id<"serviceaccount">;
  definitionText: string;
  pipeline: Pipeline;
  /**
   * Pre-read prompt file contents — the Automation queue path. The queue
   * snapshots the definition *and* its prompt files at event time ("definisi
   * dari ref yang dipicu"), so a drain must not re-read them from a ref that
   * may have moved since. Omitted for the direct paths, which read live from
   * `refSha`.
   */
  definitionFiles?: Record<string, string>;
}

export interface GrillingSummary {
  draftRevisions: number;
  humanEdits: number;
  decisions: number;
  openQuestions: number;
}

export interface RewindRunInput {
  id: Id<"run">;
  parentRunId: Id<"run">;
  stepRunId: Id<"steprun">;
}

/** A Step is materializable up front iff it has no unmet dependency and is not itself a fan-out source — see the file-level doc for why this is narrower than "every non-fan-out Step". */
function materializableRootStepIds(pipeline: Pipeline): string[] {
  return Object.entries(pipeline.steps)
    .filter(([, step]) => step.after.length === 0 && step.branches === undefined && step.branchesFrom === undefined)
    .map(([id]) => id);
}

/**
 * Every distinct `promptFile:` the Pipeline references — top-level Steps and
 * each Branch's *effective* one (its own, or inherited from the parent
 * Step). Collected across the whole Pipeline, not just the materializable
 * subset: the Run's copy of prompt file contents must survive the
 * definition changing or disappearing later, including for Steps that
 * haven't materialized yet (spec: Run "menyimpan salinan penuh ...
 * sehingga tetap terbaca meskipun definisi aslinya berubah atau hilang").
 */
function collectPromptFilePaths(pipeline: Pipeline): string[] {
  const paths = new Set<string>();
  for (const step of Object.values(pipeline.steps)) {
    if (step.promptFile) paths.add(step.promptFile);
    if (step.branches) {
      for (const branch of step.branches) {
        const effective = branch.promptFile ?? step.promptFile;
        if (effective) paths.add(effective);
      }
    }
  }
  return [...paths];
}

/** Every issue already carries a line/column via `validatePipelineDefinition` — this just flattens them into the one-string `message` the error envelope has room for (spec: "pesan yang menunjuk baris"). Exported for `domain/pipeline-editor.ts` — validation failures answer the same way on every surface. */
export function formatValidationIssues(issues: ValidationIssue[]): string {
  return issues
    .map((issue) => {
      const location = issue.line !== null ? `line ${issue.line}` : issue.path.join(".") || "(root)";
      return `${location}: ${issue.message}`;
    })
    .join("; ");
}

function isUniqueViolation(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    (error as { code: unknown }).code === "23505"
  );
}

/**
 * Every Step (and each Branch's *effective* `runsOn`, which falls back to the
 * parent Step's) that asks for `exec:host`. `exec:docker` is the default and
 * needs no Project permission; host execution is a conscious, Project-scoped
 * opt-in (spec: "runsOn: [exec:host] hanya jalan bila Project punya
 * izinnya"; `projects.host_exec_allowed`).
 */
function hostExecSteps(pipeline: Pipeline): string[] {
  const asksHost = (runsOn: string[] | undefined): boolean => runsOn?.includes("exec:host") ?? false;
  const out: string[] = [];
  for (const [stepId, step] of Object.entries(pipeline.steps)) {
    if (asksHost(step.runsOn)) {
      out.push(stepId);
      continue;
    }
    for (const branch of step.branches ?? []) {
      if (asksHost(branch.runsOn ?? step.runsOn)) {
        out.push(`${stepId}.${branch.key}`);
      }
    }
  }
  return out;
}

async function findRepositoryByName(
  deps: Pick<AppDeps, "db">,
  projectId: Id<"project">,
  name: string,
): Promise<typeof repositories.$inferSelect | undefined> {
  const [repo] = await deps.db
    .select()
    .from(repositories)
    .where(and(eq(repositories.projectId, projectId), eq(repositories.name, name)));
  return repo;
}

/**
 * Root Steps that are fan-out sources — materialized at trigger by giving
 * birth to their branches directly, since they have no upstream to wait for
 * ("Step non-fan-out di muka, cabang saat hulu sukses": a root fan-out's
 * `branches:` list *is* the "di muka"). A root `branchesFrom:` has no
 * upstream Output at trigger, so it stays unmaterialized until its source
 * Step succeeds (`graph-advance.ts` treats `branchesFrom.step` as a
 * dependency).
 */
function rootFanOutConstantStepIds(pipeline: Pipeline): string[] {
  return Object.entries(pipeline.steps)
    .filter(([, step]) => step.after.length === 0 && isFanOutStep(step) && step.branches !== undefined)
    .map(([id]) => id);
}

/**
 * Reads every prompt file a Pipeline references at an exact sha, enforcing
 * presence and the combined size cap. Shared by `materializeRun` (direct
 * paths read live) and Automation's queue snapshot (which must read at event
 * time, before the ref can move). Throws `DomainValidationError` on a
 * missing file or an over-limit total.
 */
export async function readPromptFiles(
  deps: Pick<AppDeps, "gitHost">,
  repoRef: RepoRef,
  sha: string,
  refBranch: string,
  pipelineRepository: typeof repositories.$inferSelect,
  definitionText: string,
  pipeline: Pipeline,
): Promise<Record<string, string>> {
  const definitionFiles: Record<string, string> = {};
  let totalBytes = Buffer.byteLength(definitionText, "utf-8");
  for (const path of collectPromptFilePaths(pipeline)) {
    const content = await deps.gitHost.readFile(repoRef, sha, path);
    if (content === null) {
      throw new DomainValidationError(
        "prompt_file_not_found",
        `promptFile '${path}' referenced by the Pipeline does not exist on ref ${refBranch} (${sha}) in ${pipelineRepository.owner}/${pipelineRepository.name}`,
      );
    }
    definitionFiles[path] = content;
    totalBytes += Buffer.byteLength(content, "utf-8");
  }

  if (totalBytes > MAX_TOTAL_DEFINITION_BYTES) {
    throw new DomainValidationError(
      "pipeline_definition_too_large",
      `definition (${Buffer.byteLength(definitionText, "utf-8")} bytes) plus ${Object.keys(definitionFiles).length} prompt file(s) total ${totalBytes} bytes, over the ${MAX_TOTAL_DEFINITION_BYTES}-byte inline storage limit`,
    );
  }
  return definitionFiles;
}

/**
 * The shared birth of a Run and its initial Graph, inside the caller's
 * transaction. Reads every prompt file the Pipeline references at `refSha`
 * (never the default branch, never a cache), enforces the combined size cap,
 * resolves every materializable root Step's Repository, then inserts the Run
 * and its initial Graph in one commit. Throws `DomainValidationError` for
 * any of the input-shaped rejections; unique violations are the caller's to
 * interpret (manual: `run_id_conflict`; Automation: the (Pipeline, SHA)
 * dedup). Runs inside `db` — for Automation this is the same transaction
 * that decides concurrency, so "cancel the old run, then birth the new one"
 * commits atomically or not at all.
 */
export async function materializeRun(
  deps: Pick<AppDeps, "db" | "gitHost" | "clock">,
  db: Database,
  input: MaterializeRunInput,
): Promise<TriggeredRun> {
  const { project, pipelineRepository, pipeline } = input;
  const repoRef: RepoRef = { owner: pipelineRepository.owner, name: pipelineRepository.name };

  // AC8: `runsOn: [exec:host]` is a per-Project opt-in (`hostExecAllowed`,
  // default off). Rejected here, at the door, so a Project that never granted
  // host execution cannot have host-mode Steps scheduled onto its Runners —
  // the Runner never even sees the claim. `exec:docker` (the default, or
  // written explicitly) is never gated.
  const hostSteps = hostExecSteps(pipeline);
  if (hostSteps.length > 0 && !project.hostExecAllowed) {
    throw new DomainValidationError(
      "host_exec_not_allowed",
      `this Project has not enabled host execution, but the Pipeline runs ${hostSteps.join(", ")} on [exec:host]`,
    );
  }

  const definitionFiles =
    input.definitionFiles ??
    (await readPromptFiles(deps, repoRef, input.refSha, input.refBranch, pipelineRepository, input.definitionText, pipeline));

  // Resolve every materializable Step's repo before inserting the Run — an
  // unknown repo name is a validation error, and a validation error must not
  // leave a partial Run behind (the transaction rolls back).
  const rootStepIds = materializableRootStepIds(pipeline);
  const stepRepositoryByStepId = new Map<string, typeof repositories.$inferSelect>();
  for (const stepId of rootStepIds) {
    const step = pipeline.steps[stepId]!;
    const repoName = step.repo ?? pipeline.repo;
    const stepRepo = await findRepositoryByName(deps, project.id, repoName);
    if (!stepRepo) {
      throw new DomainValidationError(
        "step_repository_not_found",
        `Step '${stepId}' references repo '${repoName}', which is not a Repository of this Project`,
      );
    }
    stepRepositoryByStepId.set(stepId, stepRepo);
  }

  const readyAt = deps.clock.now();

  const [insertedRun] = await db
    .insert(runs)
    .values({
      id: input.id,
      projectId: project.id,
      pipelineRepositoryId: pipelineRepository.id,
      pipelinePath: input.pipelinePath,
      triggerKind: input.triggerKind,
      triggeredByPrincipalId: input.triggeredByPrincipalId,
      credentialPrincipalId: input.credentialPrincipalId,
      refBranch: input.refBranch,
      refSha: input.refSha,
      definition: input.definitionText,
      definitionFiles,
    })
    .returning();

  const createdStepRuns: StepRun[] = [];
  for (const stepId of rootStepIds) {
    const step = pipeline.steps[stepId]!;
    const stepRepo = stepRepositoryByStepId.get(stepId)!;
    const [stepRun] = await db
      .insert(stepRuns)
      .values({
        id: generateId("steprun"),
        runId: insertedRun!.id,
        repositoryId: stepRepo.id,
        stepKey: stepId,
        branchKey: null,
        turn: 1,
        attempt: 1,
        outcome: "ready",
        kind: step.kind ?? null,
        requiredTags: step.runsOn ?? [],
        readyAt,
      })
      .returning();
    createdStepRuns.push(stepRun!);
  }

  // Root `branches:` fan-outs are born at trigger, in the same transaction
  // as the Run itself (issue #11, AC5). A failed root fan-out (empty list,
  // duplicate keys, unknown branch repo) leaves a `failed` decision row. The
  // branch rows (and any decision rows) are appended to the initial Graph.
  for (const stepId of rootFanOutConstantStepIds(pipeline)) {
    await materializeFanOut({ db, now: deps.clock.now }, insertedRun!, pipeline, stepId);
  }
  const fanOutRows = await db
    .select()
    .from(stepRuns)
    .where(and(eq(stepRuns.runId, insertedRun!.id), isNotNull(stepRuns.branchKey)));
  createdStepRuns.push(...fanOutRows);

  return { run: insertedRun!, stepRuns: createdStepRuns };
}
/**
 * Triggers a Pipeline over `input.refBranch`: reads the definition and every
 * prompt file it references from that ref (never the default branch),
 * validates, and — if valid — materializes the Run and its initial Graph in
 * one Postgres transaction. Rejects before any row exists on: a missing
 * ref, a missing definition file, a definition that fails
 * `validatePipelineDefinition`, a combined size over
 * {@link MAX_TOTAL_DEFINITION_BYTES}, or a Step `repo:` that doesn't name a
 * Repository of this Project.
 */
export async function triggerRun(
  deps: Pick<AppDeps, "db" | "clock" | "gitHost">,
  principal: Principal,
  projectId: Id<"project">,
  input: TriggerRunInput,
): Promise<TriggeredRun> {
  await requireProjectMembership(deps, principal, projectId);

  const [pipelineRepository] = await deps.db
    .select()
    .from(repositories)
    .where(and(eq(repositories.id, input.repositoryId), eq(repositories.projectId, projectId)));
  if (!pipelineRepository) {
    throw new NotFoundError("repository", input.repositoryId);
  }
  const repoRef: RepoRef = { owner: pipelineRepository.owner, name: pipelineRepository.name };

  let sha: string;
  try {
    sha = await deps.gitHost.resolveRef(repoRef, input.refBranch);
  } catch (error) {
    if (error instanceof RefNotFoundError) {
      throw new DomainValidationError("ref_not_found", error.message);
    }
    throw error;
  }

  const definitionText = await deps.gitHost.readFile(repoRef, sha, input.pipelinePath);
  if (definitionText === null) {
    throw new DomainValidationError(
      "pipeline_definition_not_found",
      `no file at ${input.pipelinePath} on ref ${input.refBranch} (${sha}) in ${pipelineRepository.owner}/${pipelineRepository.name}`,
    );
  }

  const validation = validatePipelineDefinition(definitionText);
  if (!validation.valid) {
    throw new DomainValidationError("pipeline_definition_invalid", formatValidationIssues(validation.issues));
  }
  const { pipeline } = validation;

  // AC8: `runsOn: [exec:host]` is a per-Project opt-in (`hostExecAllowed`,
  // default off). Rejected here, at the door, so a Project that never granted
  // host execution cannot have host-mode Steps scheduled onto its Runners —
  // the Runner never even sees the claim. `exec:docker` (the default, or
  // written explicitly) is never gated.
  const [project] = await deps.db.select().from(projects).where(eq(projects.id, projectId));
  const hostSteps = hostExecSteps(pipeline);
  if (hostSteps.length > 0 && !project?.hostExecAllowed) {
    throw new DomainValidationError(
      "host_exec_not_allowed",
      `this Project has not enabled host execution, but the Pipeline runs ${hostSteps.join(", ")} on [exec:host]`,
    );
  }

  // Fallback User→ServiceAccount (spec: "Credential, secret, dan akses
  // repo"). A User-triggered Run's `credentialPrincipalId` defaults to the
  // User itself — the Run uses secrets that User owns. When the Project has
  // `allowSharedAgentCredential` on AND the User owns no secrets of their own
  // here, the Run falls back to the Project's ServiceAccount so it can still
  // reach the Project's shared credentials. The two attribution columns on
  // `runs` differ exactly when the fallback engaged (spec: "pemakaiannya
  // terlihat lewat dua kolom atribusi terpisah di `runs`"). Automation runs
  // (ServiceAccount-triggered) always attribute to the ServiceAccount — no
  // fallback, no flag needed.
  let credentialPrincipalId: Id<"user"> | Id<"serviceaccount"> = principal.id;
  if (principal.kind === "user" && project?.allowSharedAgentCredential) {
    const [userOwnedSecret] = await deps.db
      .select({ id: secrets.id })
      .from(secrets)
      .where(and(eq(secrets.projectId, projectId), eq(secrets.ownerPrincipalId, principal.id)))
      .limit(1);
    if (!userOwnedSecret) {
      const [shared] = await deps.db
        .select()
        .from(serviceAccounts)
        .where(eq(serviceAccounts.projectId, projectId))
        .orderBy(asc(serviceAccounts.principalId))
        .limit(1);
      if (shared) {
        credentialPrincipalId = shared.principalId;
      }
    }
  }

  let result: TriggeredRun;
  try {
    result = await deps.db.transaction(async (tx) =>
      materializeRun(deps, tx, {
        id: input.id,
        project: project!,
        pipelineRepository,
        pipelinePath: input.pipelinePath,
        refBranch: input.refBranch,
        refSha: sha,
        triggerKind: "manual",
        triggeredByPrincipalId: principal.id,
        credentialPrincipalId,
        definitionText,
        pipeline,
      }),
    );
  } catch (error) {
    if (isUniqueViolation(error)) {
      throw new DomainValidationError("run_id_conflict", `a Run with id ${input.id} already exists`);
    }
    throw error;
  }

  await recordAuditEvent(deps, {
    actor: principal,
    projectId,
    action: "run.triggered",
    targetType: "run",
    targetId: result.run.id,
    metadata: { pipelinePath: input.pipelinePath, refBranch: input.refBranch, refSha: sha },
  });

  return result;
}

/** Records cancellation intent; live StepRuns are cancelled by the normal background/heartbeat path. */
export async function cancelRun(
  deps: Pick<AppDeps, "db" | "clock">,
  principal: Principal,
  projectId: Id<"project">,
  runId: Id<"run">,
): Promise<Run> {
  await requireProjectMembership(deps, principal, projectId);
  const [existing] = await deps.db
    .select()
    .from(runs)
    .where(and(eq(runs.id, runId), eq(runs.projectId, projectId)));
  if (!existing) {
    throw new NotFoundError("run", runId);
  }

  if (existing.cancelRequestedAt !== null || existing.endedAt !== null) {
    return existing;
  }

  const [updated] = await deps.db
    .update(runs)
    .set({ cancelRequestedAt: deps.clock.now() })
    .where(and(eq(runs.id, runId), isNull(runs.cancelRequestedAt), isNull(runs.endedAt)))
    .returning();

  if (updated) {
    await recordAuditEvent(deps, {
      actor: principal,
      projectId,
      action: "run.cancel_requested",
      targetType: "run",
      targetId: runId,
    });
    return updated;
  }

  const [winner] = await deps.db
    .select()
    .from(runs)
    .where(and(eq(runs.id, runId), eq(runs.projectId, projectId)));
  if (!winner) {
    throw new NotFoundError("run", runId);
  }
  return winner;
}

/** ID-only write variants for the web contract's `/runs/:id/*` actions. */
export async function cancelRunById(
  deps: Pick<AppDeps, "db" | "clock">,
  principal: Principal,
  runId: Id<"run">,
): Promise<Run> {
  const [run] = await deps.db.select().from(runs).where(eq(runs.id, runId));
  if (!run) throw new NotFoundError("run", runId);
  return cancelRun(deps, principal, run.projectId, runId);
}

/**
 * Rewinds by cloning the existing timeline into a new Run and resetting one
 * selected StepRun to `ready`. The old Run, its questions, and its Artifacts
 * remain untouched; `parent_run_id` is the only lineage marker needed.
 */
export async function rewindRun(
  deps: Pick<AppDeps, "db" | "clock">,
  principal: Principal,
  projectId: Id<"project">,
  input: RewindRunInput,
): Promise<TriggeredRun> {
  await requireProjectMembership(deps, principal, projectId);
  const [sourceRun] = await deps.db
    .select()
    .from(runs)
    .where(and(eq(runs.id, input.parentRunId), eq(runs.projectId, projectId)));
  if (!sourceRun) {
    throw new NotFoundError("run", input.parentRunId);
  }
  const [target] = await deps.db
    .select()
    .from(stepRuns)
    .where(and(eq(stepRuns.id, input.stepRunId), eq(stepRuns.runId, sourceRun.id)));
  if (!target) {
    throw new NotFoundError("step run", input.stepRunId);
  }
  if (input.id === sourceRun.id) {
    throw new DomainValidationError("run_id_conflict", "the rewound Run must have a new id");
  }

  const sourceStepRuns = await deps.db
    .select()
    .from(stepRuns)
    .where(and(eq(stepRuns.runId, sourceRun.id), lt(stepRuns.turn, target.turn + 1)));
  const sourceQuestions = await deps.db
    .select()
    .from(questions)
    .where(inArray(questions.stepRunId, sourceStepRuns.map((row) => row.id)));
  const sourceArtifacts = await deps.db
    .select()
    .from(artifacts)
    .where(inArray(artifacts.stepRunId, sourceStepRuns.map((row) => row.id)));
  const now = deps.clock.now();

  try {
    const result = await deps.db.transaction(async (tx) => {
      const [child] = await tx
        .insert(runs)
        .values({
          id: input.id,
          projectId: sourceRun.projectId,
          pipelineRepositoryId: sourceRun.pipelineRepositoryId,
          pipelinePath: sourceRun.pipelinePath,
          triggerKind: "manual",
          triggeredByPrincipalId: principal.id,
          credentialPrincipalId: sourceRun.credentialPrincipalId,
          refBranch: sourceRun.refBranch,
          refSha: sourceRun.refSha,
          parentRunId: sourceRun.id,
          definition: sourceRun.definition,
          definitionFiles: sourceRun.definitionFiles,
        })
        .returning();

      const idBySourceStepRun = new Map<Id<"steprun">, Id<"steprun">>();
      const createdStepRuns: StepRun[] = [];
      const previous = sourceStepRuns.find(
        (row) =>
          row.stepKey === target.stepKey &&
          row.branchKey === target.branchKey &&
          row.turn === target.turn - 1,
      );
      for (const row of sourceStepRuns) {
        const isTarget = row.id === target.id;
        const id = generateId("steprun");
        idBySourceStepRun.set(row.id, id);
        const [created] = await tx
          .insert(stepRuns)
          .values({
            id,
            runId: child!.id,
            repositoryId: row.repositoryId,
            stepKey: row.stepKey,
            branchKey: row.branchKey,
            turn: row.turn,
            attempt: isTarget ? 1 : row.attempt,
            outcome: isTarget ? "ready" : row.outcome,
            reason: isTarget ? null : row.reason,
            kind: row.kind,
            requiredTags: row.requiredTags,
            readyAt: isTarget ? now : row.readyAt,
            startedAt: isTarget ? null : row.startedAt,
            leasedBy: null,
            leaseToken: null,
            leaseExpiresAt: null,
            outputRefBranch: isTarget ? previous?.outputRefBranch ?? null : row.outputRefBranch,
            outputRefSha: isTarget ? previous?.outputRefSha ?? null : row.outputRefSha,
            outputData: isTarget ? null : row.outputData,
            prNumber: isTarget ? null : row.prNumber,
            prUrl: isTarget ? null : row.prUrl,
            finalPrompt: isTarget ? null : row.finalPrompt,
            sessionBlobKey: row.sessionBlobKey,
            sessionId: row.sessionId,
            resumePrompt: row.resumePrompt,
            sessionPurgedAt: row.sessionPurgedAt,
          })
          .returning();
        if (created) createdStepRuns.push(created);
      }

      for (const question of sourceQuestions) {
        const newStepRunId = idBySourceStepRun.get(question.stepRunId);
        if (!newStepRunId || question.stepRunId === target.id) continue;
        await tx.insert(questions).values({
          id: generateId("question"),
          stepRunId: newStepRunId,
          kind: question.kind,
          body: question.body,
          options: question.options,
          multi: question.multi,
          allowOther: question.allowOther,
          artifactKey: question.artifactKey,
          groupId: question.groupId,
          createdAt: question.createdAt,
          answeredAt: question.answeredAt,
          answeredByPrincipalId: question.answeredByPrincipalId,
          answer: question.answer,
        });
      }
      for (const artifact of sourceArtifacts) {
        const newStepRunId = idBySourceStepRun.get(artifact.stepRunId);
        if (!newStepRunId || artifact.stepRunId === target.id) continue;
        await tx.insert(artifacts).values({
          id: generateId("artifact"),
          stepRunId: newStepRunId,
          key: artifact.key,
          kind: artifact.kind,
          contentType: artifact.contentType,
          blobKey: artifact.blobKey,
          sizeBytes: artifact.sizeBytes,
          authoredByPrincipalId: artifact.authoredByPrincipalId,
          createdAt: artifact.createdAt,
        });
      }
      return { run: child!, stepRuns: createdStepRuns };
    });
    await recordAuditEvent(deps, {
      actor: principal,
      projectId,
      action: "run.triggered",
      targetType: "run",
      targetId: result.run.id,
      metadata: { parentRunId: sourceRun.id, rewindStepRunId: target.id },
    });
    return result;
  } catch (error) {
    if (isUniqueViolation(error)) {
      throw new DomainValidationError("run_id_conflict", `a Run with id ${input.id} already exists`);
    }
    throw error;
  }
}

export async function rewindRunById(
  deps: Pick<AppDeps, "db" | "clock">,
  principal: Principal,
  input: RewindRunInput,
): Promise<TriggeredRun> {
  const [run] = await deps.db.select().from(runs).where(eq(runs.id, input.parentRunId));
  if (!run) throw new NotFoundError("run", input.parentRunId);
  return rewindRun(deps, principal, run.projectId, input);
}

function decisionsIn(outputData: unknown): number {
  if (typeof outputData !== "object" || outputData === null) return 0;
  const topLevel = (outputData as { decisions?: unknown }).decisions;
  if (Array.isArray(topLevel)) return topLevel.length;
  const outputs = (outputData as { outputs?: unknown }).outputs;
  if (typeof outputs !== "object" || outputs === null) return 0;
  const nested = (outputs as { decisions?: unknown }).decisions;
  return Array.isArray(nested) ? nested.length : 0;
}

/** Four reopen numbers, all derived from immutable state at read time. */
export async function getGrillingSummary(
  deps: Pick<AppDeps, "db">,
  principal: Principal,
  projectId: Id<"project">,
  runId: Id<"run">,
): Promise<GrillingSummary> {
  await requireProjectMembership(deps, principal, projectId);
  const [run] = await deps.db
    .select({ id: runs.id })
    .from(runs)
    .where(and(eq(runs.id, runId), eq(runs.projectId, projectId)));
  if (!run) {
    throw new NotFoundError("run", runId);
  }

  const [revisionCount] = await deps.db
    .select({ value: count() })
    .from(artifacts)
    .innerJoin(stepRuns, eq(stepRuns.id, artifacts.stepRunId))
    .where(and(eq(stepRuns.runId, runId), eq(artifacts.key, "prd")));
  const [humanEditCount] = await deps.db
    .select({ value: count() })
    .from(artifacts)
    .innerJoin(stepRuns, eq(stepRuns.id, artifacts.stepRunId))
    .where(
      and(
        eq(stepRuns.runId, runId),
        eq(artifacts.key, "prd"),
        isNotNull(artifacts.authoredByPrincipalId),
      ),
    );
  const [openQuestionCount] = await deps.db
    .select({ value: count() })
    .from(questions)
    .innerJoin(stepRuns, eq(stepRuns.id, questions.stepRunId))
    .where(
      and(
        eq(stepRuns.runId, runId),
        isNull(questions.answeredAt),
        eq(stepRuns.outcome, "awaiting-human"),
      ),
    );
  const outputRows = await deps.db
    .select({ outputData: stepRuns.outputData })
    .from(stepRuns)
    .where(eq(stepRuns.runId, runId));

  return {
    draftRevisions: Number(revisionCount?.value ?? 0),
    humanEdits: Number(humanEditCount?.value ?? 0),
    decisions: outputRows.reduce((total, row) => total + decisionsIn(row.outputData), 0),
    openQuestions: Number(openQuestionCount?.value ?? 0),
  };
}

export interface RunListFilters {
  /** `ended_at IS NULL` — distinct from `outcome`, never combined with it (spec: "filter ... terpisah tegas"). */
  inFlight?: boolean;
  /** `outcome = ...` — a Run's final verdict. */
  outcome?: "succeeded" | "failed" | "cancelled";
}

export interface RunPage {
  runs: Run[];
  /** Null when this page was not full — there is no total count (spec: "tanpa total count"). */
  nextCursor: Id<"run"> | null;
}

/** Keyset pagination on `id` DESC (newest first) — never offset (spec: "daftar yang di-poll 3 detik bergeser di bawah pembaca"). */
export async function listRuns(
  deps: Pick<AppDeps, "db">,
  principal: Principal,
  projectId: Id<"project">,
  filters: RunListFilters,
  cursor: Id<"run"> | null,
  limit: number,
): Promise<RunPage> {
  await requireProjectMembership(deps, principal, projectId);

  const conditions = [eq(runs.projectId, projectId)];
  if (filters.inFlight) {
    conditions.push(isNull(runs.endedAt));
  }
  if (filters.outcome) {
    conditions.push(eq(runs.outcome, filters.outcome));
  }
  if (cursor) {
    conditions.push(lt(runs.id, cursor));
  }

  const rows = await deps.db
    .select()
    .from(runs)
    .where(and(...conditions))
    .orderBy(desc(runs.id))
    .limit(limit + 1);

  const hasMore = rows.length > limit;
  const page = hasMore ? rows.slice(0, limit) : rows;
  const nextCursor = hasMore ? (page[page.length - 1]!.id as Id<"run">) : null;

  return { runs: page, nextCursor };
}

export interface RunWithGraph {
  run: Run;
  stepRuns: StepRun[];
}

/** One Run plus its materialized Graph so far — the placeholder for anything not yet materialized is a UI concern, not a row (spec: 06-dag "simpul placeholder"). */
export async function getRun(
  deps: Pick<AppDeps, "db">,
  principal: Principal,
  projectId: Id<"project">,
  runId: Id<"run">,
): Promise<RunWithGraph> {
  await requireProjectMembership(deps, principal, projectId);

  const [run] = await deps.db.select().from(runs).where(and(eq(runs.id, runId), eq(runs.projectId, projectId)));
  if (!run) {
    throw new NotFoundError("run", runId);
  }

  const graph = await deps.db.select().from(stepRuns).where(eq(stepRuns.runId, runId));
  return { run, stepRuns: graph };
}
